version: 1.0.1
os: linux
files:
  - source: /index.html
    destination: /usr/share/nginx/vue-resume
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
    - location: scripts/build.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/run_prod.sh
      timeout: 300
      runas: root

