version: 0.2

phases:
  install:
    commands:
      - cd client
      - echo "install yarn"
      - npm install -g yarn
  pre_build:
    commands:
      - echo "yarn install"
      - yarn install
  build:
    commands:
      - echo "install build"
      - yarn build
  post_build:
    commands:
      - echo run successfuly
artifacts:
  files:
    - '**/*'
  base-directory: dist
