version: 0.2

phases:
  install:
    commands:
      - echo "install yarn"
      - npm install -g yarn
  pre_build:
    commands:
      - echo "install install"
      - yarn install
  build:
    commands:
      - echo "install build"
      - yarn build
  post_build:
    commands:
      - echo nothing to do
artifacts:
  files:
    - '**/*'
  base-directory: dist
